services:
  db:
    image: mysql:8.0
    container_name: 'nest-rest'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 5002:3306
    restart: always
    volumes:
      - ./mysql-data:/var/lib/mysql
